defaults: &defaults
  working_directory: &workspace_root ~/tmp
  docker:
    - image: lindard/circle-sauce-node

references:
  persist_to_workspace: &persist_to_workspace
      persist_to_workspace:
        root: *workspace_root
        paths: 
        - ./

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

version: 2
jobs:
  build:
    <<: *defaults
    steps: 
      - checkout
      - run:  
          name: npm install
          command: |
            npm install
      - *persist_to_workspace

  test: 
    <<: *defaults
    steps:
      - *attach_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker
      - run:  
          name: create proxy tunnel
          command: |
            docker run --rm -it -p 8080:80 lindard/circle-sauce-node -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i builtbycircle --readyfile ~/sauce_is_ready:
                background: true
            # sleep 1
            # wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
            # while ! grep -m1 'Sauce Connect is up, you may start your tests.
            # sleep 1
            # done
            echo Sauce-Connect is up and running
            npm sauceLight
            kill $(cat pid)
      - run: 
          name: run sauce labs test
          command: |
            npm sauceLight
      - run:
          name: Shut Down Sauce Connect Tunnel
          command: |
            killall sc
                  
workflows:
    version: 2

    build-test-deploy:
      jobs:
      - build
      - test:
          requires:
            - build