version: 2
jobs:
  build:
    docker:
      - image: lindard/circleci
    steps: 
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker
      - run:  | 
          docker run --rm -it -p 8080:80 lindard/circleci -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i builtbycircle
      - run:
                name: Shut Down Sauce Connect Tunnel
                command: |
                  killall sc    
      # - run:  | 
      #     name: build
      #     command: |
      #       node nightwatch.conf.js
      #       npm run sauceLight
      # - run:
      #     name: Shut Down Sauce Connect Tunnel
      #     command: |
      #       kill -9 `cat /tmp/sc_client.pid`