version: 2
jobs:
  build:
    docker:
      - image: lindard/circleci
    steps: 
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker
      - run:  | 
          docker run --rm -it -p 8080:80 http://hub.docker.com/r/lindard/circleci -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i BuiltByCircleCi